#!/bin/bash
source /etc/rht
history | awk '/\<lab\> / {print $(NF-3),$(NF-2),$(NF-1),$(NF)}' > ~/.lab_history 
curl -X POST -F '.lab_history=@.lab_history' -F "RHT_COURSE=$RHT_COURSE" http://lab-api.apps.ocp4.zero-effort.net/upload
